trigger:

  branches:
    include:
      - main

pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none

  - script: |
      target_file_name="schema.json"
      if [ -d "tution" ]; then
        echo "Removing existing tution directory"
        rm -rf tution
      fi

      echo "Cloning test branch..."
      git clone -b test https://github.com/debayanChakra/tution.git

      echo "Listing contents..."
      ls -la tution
    displayName: Clone repo and list schema file
  - script: |
      echo "Installing AzCopy..."
      wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
      tar -xf azcopy.tar.gz
      AZCOPY_DIR=$(find . -type d -name "azcopy_linux*")
      sudo cp "$AZCOPY_DIR/azcopy" /usr/local/bin/
      azcopy --version
    displayName: Install AzCopy

  



 