trigger:
  branches:
    include:
      - main
pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none 
  - script: |
      target_file_name="schema.json"
      if [ -d "tution" ]; then
        echo "Removing existing tution directory"
        rm -rf tution
        ls -la
      fi
      git clone -b test https://github.com/debayanChakra/tution.git
      cd tution
      ls -la
      pwd
      file_path=${pwd}/${target_file_name}
      echo $file_path
      azcopy copy $file_path 'https://pramit46.dfs.core.windows.net/schema/schema' --recursive
    
