trigger:
  branches:
    include:
      - test


pool:
  name: 'vstsvm-pool'

steps:
  - script: |
      git checkout test
      echo "Now on branch: $(git branch --show-current)"
      git pull origin test
      ls -la
