trigger:
  branches:
    include:
      - main
pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none 
  - script: |
      if [ -d "tution" ]; then
        echo "Removing existing tution directory"
        rm -rf tution
        ls -la
      fi
      git clone -b test https://github.com/debayanChakra/tution.git
      cd tution
      ls -la
