trigger:
  branches:
    include:
      - main
pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none 
  - script: |
      target_file_name="schema.json"
      if [ -d "tution" ]; then
        echo "Removing existing tution directory"
        rm -rf tution
        ls -la
      fi
      git clone -b test https://github.com/debayanChakra/tution.git
      cd tution
      ls -la
      pwd
      file_path=${pwd}/${target_file_name}
      echo $file_path
      az storage blob upload \
        --account-name  pramit46\
        --container-name  schema\
        --name /schema/schema.json \
        --file  $file_path\
        --auth-mode key \
        --account-key "1RPWtYkx2kgXfPEb7EEja/TdLtXPWMIL1/sdRoi9E2t0xigDAu0w7GZNbppwSRlrMCxwDuQEQN4p+AStWNqxFQ=="

    
