trigger:
  branches:
    include:
      - main
pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none 
  - script: |
      git clone https://github.com/debayanChakra/tution.git
      git checkout -b test
      cd tution
      ls -la
