trigger:
  branches:
    include:
      - test


pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none 

steps:
  - script: |
      git clone https://github.com/debayanChakra/tution.git
      git checkout -b test
      ls -la
