trigger:
  branches:
    include:
      - main

pool:
  name: 'vstsvm-pool'

steps:
  - checkout: none

  - script: |
      target_file_name="schema.json"
      if [ -d "tution" ]; then
        echo "Removing existing tution directory"
        rm -rf tution
      fi

      echo "Cloning test branch..."
      git clone -b test https://github.com/debayanChakra/tution.git

      echo "Listing contents..."
      ls -la tution
    displayName: Clone repo and list schema file

  - task: AzureFileCopy@2
    inputs:
      SourcePath: 'tution/schema.json' 
      azureSubscription: 'My Azure Subscription(1)(3b68346a-fedc-44aa-b468-2b9ca87bb141)'
      Destination: 'AzureBlob'
      storage: 'pramit46'
      ContainerName: 'schema'
      BlobPrefix: 'schema/'
    displayName: Upload schema.json to Blob container
